HAI-1392 Implement cable report application first page
City-of-Helsinki/haitaton-ui pull request #242
Opened 2023-01-02 08:08 UTC by markohaarni

# Description

Implemented first page of cable report application to match the new design and replaced formik with react-hook-form.

### Jira Issue: https://helsinkisolutionoffice.atlassian.net/browse/HAI-1392

## Type of change

- [ ] Bug fix
- [ ] New feature
- [x] Other

# Checklist:

- [x] I have written new tests (if applicable)
- [x] I have ran the tests myself (if applicable)
- [ ] I have made necessary changes to the documentation, link to confluence
      or other location:

2023-01-02 10:13 UTC, corvidian commented on src/locales/en.json
> +      "perustiedot": "Perustiedot",
Pitäisikö näissä kääntämättömissä olla edelleen toi `EN:` etuliite, että kääntämättömät tekstit löytää helposti?

2023-01-02 10:17 UTC, corvidian commented on src/domain/johtoselvitys/BasicInfo.tsx
> +            voimassa johtojen maastonäyttöjä tilattaessa sekä Johtoselvitysta tehdessä.
> Johtoselvityksen tulee olla voimassa ...Johtoselvitystä tehdessä?
Tämä ohjeteksti taitaa kaivata vielä päivitystä? Johtoselvityksen varmaan voi tehdä ilman johtoselvitystä, ettei päädytä loputtomaan rekursioon.

2023-01-02 10:20 UTC, corvidian commented on src/domain/johtoselvitys/Contacts.tsx
> +        <TextInput id="applicationData.customerWithContacts.contacts[0].name" label="Nimi" />
Pitäisikö nämä labelit vaihtaa käännösavaimiin jo tässä PR:ssä, kun näihin riveihin kerran kosketaan? Vai tuleeko näihin kaikkiin muutoksia vielä seuraavassakin?

2023-01-02 10:43 UTC, markohaarni commented on src/locales/en.json
> +      "perustiedot": "Perustiedot",
Joo, se voisi olla hyvä. Lisään ne sinne.

2023-01-02 10:45 UTC, markohaarni commented on src/domain/johtoselvitys/BasicInfo.tsx
> +            voimassa johtojen maastonäyttöjä tilattaessa sekä Johtoselvitysta tehdessä.
Totta. Täytyy kysyä tarkennusta tuohon.

2023-01-02 10:48 UTC, markohaarni commented on src/domain/johtoselvitys/Contacts.tsx
> +        <TextInput id="applicationData.customerWithContacts.contacts[0].name" label="Nimi" />
Joo, näihin tulee muutoksia ja ajattelin, että vaihtaisin käännösavaimet silloin.

2023-01-02 11:26 UTC, markohaarni commented on src/locales/en.json
> +      "perustiedot": "Perustiedot",
Etuliitteet lisätty.

2023-01-02 11:28 UTC, corvidian requested changes
Tämä PR rikkoo nykyisen, jo sinällään toimivan, sivun johtoselvitysilmoitusten lähettämiselle. Johtoselvityshakemuksiin liittyen tehdään muutakin kehitystä, joka vaikeutuu huomattavasti jos hakemuksia ei voi luoda kälin kautta.

Voisiko uutta versiota kasata johonkin muualle kunnes se on valmis, tai kopioida vanha sivu johonkin toiseen osoitteeseen?

2023-01-02 11:44 UTC, markohaarni commented
Tein oman branchin, johon kasata uusi tämä uusi versio.

2023-01-03 08:53 UTC, markohaarni commented
Edellinen versio lomakkeesta palautettu ja se löytyy osoitteesta /johtoselvityshakemusvanha

2023-01-04 07:55 UTC, corvidian approved these changes

2023-01-04 09:42 UTC, merged