HAI-306: UI: Organisaatiovalinta ja käyttäjän syöttämä arvo
City-of-Helsinki/haitaton-ui pull request #83
Opened 2021-01-24 17:31 UTC by valger10

2021-01-25 07:35 UTC, petteriinnanmaa requested changes
Sain sivun JS:n kaatumaan jossain tilanteessa kun painoin "Tallenna luonnos". Kenttien muuttaminen ei päivitä formin statea niin esim. tallenna-napit eivät toimi oikein. Lisäksi tämä toteutus ei toimi enää tulevaisuudessa, kun yhteystietoja halutaan lisätä useampia. 

Pitäisikö checkboxin state lisätä react-hook-formin stateen, HankeContact -tyypin sisään?

2021-01-27 13:46 UTC, mikko-kujapelto commented on src/domain/hanke/edit/types.ts
> +  checked: any;
Mikä tämä checked arvo on? 🤔 
Olisiko tyypitys kuitenkin mahdollista ilman disabloimatta eslinttiä ja antamalla sille anyä?

2021-01-27 14:06 UTC, mikko-kujapelto requested changes
Tässä oli mukana aika paljon eslint-disableja (varsinkin src/domain/hanke/edit/Form2.tsx), lähtökohtana voitaisiin pitää että eslinttiä ei disabloida vaan pystytään ratkaisemaan sen nostamat virheet.
imo ei näin paljon eslint ja tslint disablointia, ne on siellä kuitenkin kehittäjän turvana 👨‍🚀 toki poikkeustapauksia on myös olemassa.
Tsekkaan myöhemmin haaran lokaalina ja kuikuilen mitä virheitä näillä disabloinneilla on kierrelty ja joskos niihin löytyisi ratkaisuja 👨‍🎨 

Katson samalla myös näiden listojen accessointia. Suorilla indekseillä viittaukset eivät jotenkin tunnu mukavilta. 🤔

2021-01-27 14:06 UTC, mikko-kujapelto commented on src/domain/hanke/edit/Form2.tsx
> +  const forceUpdate = React.useState()[1].bind(null, {});
Taisiis, uskoakseni komponentti ei ole syystä tai toisesta päivittynyt, itse koen tärkeäksi että komponenttien lifecyclen ymmärryksen kautta (mikä aiheuttaa komponentin re-rendauksen) tehtäisiin toimiva toteutus, eikä lisättäisi häckkejä jotka pakottavat komponentin re-rendaamaan ☝️:monocle-man:

2021-01-27 14:06 UTC, mikko-kujapelto commented on src/domain/hanke/edit/Form.tsx
>      console.log(data);
jäänyt joku yksittäinen console.logi

2021-01-27 14:06 UTC, mikko-kujapelto commented on src/domain/hanke/edit/Form.test.tsx
> +    // expect(handleSave).toHaveBeenCalledTimes(2);
? disabloitu

2021-01-27 14:52 UTC, petteriinn commented on src/domain/hanke/edit/Form.test.tsx
> +    // expect(handleSave).toHaveBeenCalledTimes(2);
Sanoin että voi disabloida toistaiseksi jos ei muuten ratkea. Ajattelin että sitten saa PR:n päivitettyä ja pääsen testamaan mikä on vikana. Äsken testasin ja ainakin minun ympäristössä näiden kommenttien poistaminen ei hajottanut testejä.

2021-01-29 06:11 UTC, mikko-kujapelto commented
Kävin hieman läpi testien toteutusta; nythän ne eivät varsinaisesti testaa mitään eksaktia -- toisin sanoen on automatisoitu formin täyttämistä mutta arvoja ei validoida ja varsinaiset testit eli kaikki assertit kuten expect(a.toHaveValue(y)) puuttuvat. Katsotaan läpi yhdessä, voitaisiin näitä parikoodailla ja pohtia millä tavalla näitä voisi assertoida.

Lisäksi organisaation luomiselle voisi luoda oman erillisen testinsä sen sijasta että kasvatetaan yhtä massiivista testiä.
Tätä varten voisi olla hyvä luoda joku utility komponentti mikä generoisi / täyttäisi hankkeita annetuilla parametreilla.

2021-01-29 06:29 UTC, mikko-kujapelto commented
Ehkä olin tulkinnut väärin, mutta ilmeisesti tässä ei vielä käsitellä käyttäjän syöttämää arvoa vielä?
Eli tämä on vielä jossain määrin alustavaa "leiskan staattista toteutusta" ?

Syötettyjä arvoja ei lähetetä rajapintapyynnössä ja lisäksi funktio "iniateData" (pikku kirjoitusvirhe, siis initiateDate varmaan) poikkeaa muusta formin käsittelystä enkä näe että se olisi välttämättä tarpeen.

Onko git rebase tuttu?
Voitaisiin käydä sitäkin läpi. Devin mergeäminen tähän featurehaaraan voi helposti vähän sekoittaa tilannetta kun samaan tiedostoon on tullut omia muutoksia, sekä mergen sisääntuotuja muutoksia. Rebase jättäisi tilanteen muutosten osalta selkeäksi.

Olen hieman huolestunut kun tässä alkaa tuntua olevan aika monta asiaa hieman vinossa kun tarkemmin pureutuu. Puhutaan päivällä lisää 👨‍🍳

2021-02-03 09:07 UTC, closed without merging

2021-02-03 09:08 UTC, petteriinn commented
Tehty kokonaan uusi toteutus:
https://github.com/City-of-Helsinki/haitaton-ui/pull/91