HAI-601: Axe: Hankelistan korjaus ja lisääminen testeihin
City-of-Helsinki/haitaton-ui pull request #96
Opened 2021-02-04 12:21 UTC by valger10

2021-02-04 12:31 UTC, petteriinn commented on src/domain/hanke/list/Hankelista.styles.scss
> +    span.acceText {
Mitä tarkoittaa acce? Käytä mieluummin ihan selväkielisiä nimiä, niin ei tarvitse arvailla. 

Mitä tämä tyylimäärittely käytännössä tekee?

2021-02-04 12:34 UTC, petteriinn commented on src/domain/hanke/list/Table.tsx
> +                            <IconAngleUp aria-label={t('hankeList:icons:sorting')} />
Nämä voisi siirtää pois hankeList:n alta jos joskus halutaan tehdä vastaava taulukko toiselle sivulle. Esim. common:icons:x

2021-02-04 12:40 UTC, petteriinn commented on src/domain/hanke/list/Table.tsx
> +                        <IconAngleDown aria-label={t('hankeList:icons:sortAescendent')} />
Typo? Pitäiskö olla Descenting?

2021-02-04 12:44 UTC, valger10 commented on src/domain/hanke/list/Hankelista.styles.scss
> +    span.acceText {
Se piilottaa tekstin normaalilta käyttäjältä, se vie tekstin -9999rem vasemmalle

2021-02-04 12:59 UTC, petteriinn requested changes
Nappien labelit korjattava fiksummaksi.

2021-02-04 12:59 UTC, petteriinn commented on src/domain/hanke/list/Table.tsx
>          <button
Eikös periaatteessa tällä buttonille pitäisi antaa aria-label? 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

Tähän tyyliin:
```
        <button
          id="last-page-button"
          type="button"
          aria-label={t('hankeList:buttons:toLastPage')}
        >
          <IconAngleRight aria-labelledby="last-page-button" />
          <IconAngleRight aria-labelledby="last-page-button" />
        </button>
```

2021-02-05 12:15 UTC, petteriinn commented on src/domain/hanke/list/Table.tsx
> +import IconAngleUp from '../../../common/icons/AngleUp';
Näiden "custom"-komponentit voisi poistaa ja importata tuolta hds-react/icons -kirjastosta suoraan

2021-02-05 12:19 UTC, petteriinn commented on src/common/icons/AngleDown.tsx
> +import React from 'react';
Eli tän vois poistaa.

2021-02-05 12:19 UTC, petteriinn commented on src/common/icons/AngleUp.tsx
> +import React from 'react';
Ja tän voi poistaa.

2021-02-05 13:23 UTC, petteriinn approved these changes

2021-02-05 13:28 UTC, merged